package handlers

import (
	"github.com/gorilla/mux"
	"net/http"

	_ "CsvManipulator/docs" // docs are generated by Swag CLI, you have to import it.
	httpSwagger "github.com/swaggo/http-swagger"
)

func NewRouter() *mux.Router { // NewRouter returns a new router
	router := mux.NewRouter()

	router.HandleFunc("/upload", uploadHandler).Methods(http.MethodPost)

	// Swagger endpoint
	router.PathPrefix("/swagger/").Handler(httpSwagger.WrapHandler)

	return router
}
