package handlers

import (
	"github.com/gorilla/mux"
	"net/http"

	_ "CsvManipulator/docs" // docs are generated by Swag CLI, you have to import it.
	httpSwagger "github.com/swaggo/http-swagger"
)

func (api *API) NewRouter() *mux.Router { // NewRouter returns a new router
	router := mux.NewRouter()

	router.HandleFunc("/upload", api.UploadHandler).Methods(http.MethodPost)
	router.HandleFunc("/sort-csv", api.SortCSVHandler).Methods(http.MethodPost)
	// Swagger endpoint
	router.PathPrefix("/swagger/").Handler(httpSwagger.WrapHandler)

	return router
}
